/* eslint-disable camelcase */
import { Albert_Sans } from 'next/font/google';

import './globals.css';
import Navbar from '@/layout/Navbar';

const albertSans = Albert_Sans({
  variable: '--font-albert-sans',
  subsets: ['latin'],
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className='m-0 p-0'>

      
      <body className={`${albertSans.variable} antialiased bg-black`} >
        <Navbar />
      {children}</body>
    </html>
  );
}
